package rules

import (
	"context"
	"strings"
	"testing"

	"github.com/dutifuldev/slophammer/go/internal/repo"
)

func suppressionFindings(t *testing.T, files map[string]repo.File) []Finding {
	t.Helper()
	rule := newGoSuppressionsRule(definitionByID(t, GoSuppressionsJustifiedRuleID))
	return rule.Check(context.Background(), repo.NewSnapshot("/repo", files))
}

func goFile(path string, lines ...string) repo.File {
	return repo.File{Path: path, Content: strings.Join(lines, "\n") + "\n"}
}

func TestBareNolintInProductionCodeIsAFinding(t *testing.T) {
	findings := suppressionFindings(t, map[string]repo.File{
		"internal/app.go": goFile("internal/app.go",
			"package app",
			"func run() error { return nil } //nolint:errcheck",
		),
	})

	if len(findings) != 1 {
		t.Fatalf("findings = %#v, want one", findings)
	}
	if findings[0].Path != "internal/app.go" || !strings.Contains(findings[0].Message, "(line 2)") {
		t.Fatalf("finding = %#v", findings[0])
	}
}

func TestJustifiedSuppressionsPass(t *testing.T) {
	findings := suppressionFindings(t, map[string]repo.File{
		"internal/app.go": goFile("internal/app.go",
			"package app",
			"func run() error { return nil } //nolint:errcheck // exit path already reported",
			"// the linter cannot see the build tag context here",
			"var fallback = legacy() //nolint:staticcheck",
		),
	})

	if len(findings) != 0 {
		t.Fatalf("findings = %#v, want none", findings)
	}
}

func TestEmptyNolintExplanationStaysBare(t *testing.T) {
	findings := suppressionFindings(t, map[string]repo.File{
		"internal/app.go": goFile("internal/app.go",
			"package app",
			"func run() error { return nil } //nolint:errcheck //   ",
		),
	})

	if len(findings) != 1 {
		t.Fatalf("findings = %#v, want one", findings)
	}
}

func TestSuppressionFindingReportsFirstOffensePerFile(t *testing.T) {
	findings := suppressionFindings(t, map[string]repo.File{
		"a.go": goFile("a.go",
			"package a",
			"var x = f() //nolint:errcheck",
			"var y = g() //nolint:errcheck",
		),
		"b.go": goFile("b.go",
			"package b",
			"var z = h() //nolint:errcheck",
		),
	})

	if len(findings) != 2 {
		t.Fatalf("findings = %#v, want two", findings)
	}
	if findings[0].Path != "a.go" || !strings.Contains(findings[0].Message, "(line 2)") {
		t.Fatalf("finding = %#v", findings[0])
	}
	if findings[1].Path != "b.go" {
		t.Fatalf("finding = %#v", findings[1])
	}
}

func TestNonProductionPathsAreExempt(t *testing.T) {
	paths := []string{
		"internal/app_test.go",
		"fixtures/repos/app.go",
		"templates/go/app.go",
		"internal/testdata/app.go",
		"vendor/dep/app.go",
		"scripts/tool.go",
		"internal/generated/app.go",
	}
	files := map[string]repo.File{}
	for _, path := range paths {
		files[path] = goFile(path, "package x", "var x = f() //nolint:errcheck")
	}

	if findings := suppressionFindings(t, files); len(findings) != 0 {
		t.Fatalf("findings = %#v, want none", findings)
	}
}

func TestGeneratedHeaderExemptsFile(t *testing.T) {
	findings := suppressionFindings(t, map[string]repo.File{
		"internal/model.go": goFile("internal/model.go",
			"// Code generated by protoc-gen-go. DO NOT EDIT.",
			"package model",
			"var x = f() //nolint:errcheck",
		),
	})

	if len(findings) != 0 {
		t.Fatalf("findings = %#v, want none", findings)
	}
}

func TestNonGoFilesAreIgnored(t *testing.T) {
	findings := suppressionFindings(t, map[string]repo.File{
		"README.md": {Path: "README.md", Content: "use //nolint sparingly\n"},
	})

	if len(findings) != 0 {
		t.Fatalf("findings = %#v, want none", findings)
	}
}
