version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - cyclop
    - errcheck
    - gocognit
    - ineffassign
    - staticcheck
    - unused
  settings:
    cyclop:
      max-complexity: 10
    gocognit:
      min-complexity: 15

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
